version: '3.7'
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    build: 'web'
    restart: on-failure
    hostname: web1
    command:  /usr/src/app/node_modules/.bin/nodemon server.js
    environment:
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PW}
      - DB_DBNAME=${POSTGRES_DB}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DIALECT=${DB_DIALECT}
    ports:
      - '81:5000'
    volumes:
      - ./web:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
volumes:
  db_data:
  nodemodules:
